Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

	config.vm.define "eandresS" do |server|
		server.vm.hostname = "eandresS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "virtualbox" do |vb|
			vb.name = "eandresS"
			vb.cpus = 2
			vb.memory = 2048
		end
                server.vm.provider :libvirt do |lib|
                  lib.cpus = 2
                  lib.memory = 2048
                end
	server.vm.provision "shell", path: "scripts/setup.sh"
	end
end
