Vagrant.configure("2") do |config|
  # Usamos Debian 13 (Trixie) 64-bit
  config.vm.box = "debian/bookworm64"

  # Configuración del Servidor (S)
  config.vm.define "otboumehS" do |s|
    s.vm.hostname = "otboumehS"
    s.vm.network "private_network", ip: "192.168.56.110"
    
    s.vm.provider "virtualbox" do |v|
      v.name = "otboumehS"
      v.memory = 2048
      v.cpus = 2
    end
    # Script para instalar K3s en modo Server
    s.vm.provision "shell", path: "scripts/server.sh"
  end

  # Configuración del Worker (SW)
  config.vm.define "otboumehSW" do |sw|
    sw.vm.hostname = "otboumehSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    
    sw.vm.provider "virtualbox" do |v|
      v.name = "otboumehSW"
      v.memory = 512
      v.cpus = 1
    end
    # Script para instalar K3s en modo Agent
    sw.vm.provision "shell", path: "scripts/worker.sh"
  end
end
